package com.scottishwitchcraft.controllers;

import com.scottishwitchcraft.models.Person;
import com.scottishwitchcraft.dao.IPersonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class PersonController{
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private IPersonRepository personRepo;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Person> getAll() {
        // This returns a JSON or XML with the users
        return personRepo.findAll();
    }
}
